{
 "title": "Node Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_load1{instance=~\"\\\\w+\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(sum by (cpu) (rate(node_cpu_seconds_total{instance=\"$node\",mode!=\"idle\"}[3m])))"
    }
   ]
  },
  {
   "title": "Load (5 min average)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_load5{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (cpu) (rate(node_cpu_seconds_total{instance=\"$node\",mode!=\"idle\"}[3m]))",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{instance=\"$node\",fstype!=\"tmpfs\",fstype!=\"ramfs\",mountpoint!=\"/nix/store\",mountpoint!=\"/var/tmp\"} / node_filesystem_size_bytes{instance=\"$node\",fstype!=\"tmpfs\",fstype!=\"ramfs\",mountpoint!=\"/nix/store\",mountpoint!=\"/var/tmp\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network throughput (incoming)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$node\",device!=\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network throughput (outgoing)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\",device!=\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - node_memory_MemAvailable_bytes{instance=\"$node\"}/node_memory_MemTotal_bytes{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - node_memory_SwapFree_bytes{instance=\"$node\"}/node_memory_SwapTotal_bytes{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_memory_MemAvailable_bytes{instance=\"$node\"}/node_memory_MemTotal_bytes{instance=\"$node\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "1 - node_memory_SwapFree_bytes{instance=\"$node\"}/node_memory_SwapTotal_bytes{instance=\"$node\"}",
     "legendFormat": "Swap"
    }
   ]
  }
 ]
}